POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username":"hello",
  "email":"hello@hello.com",
  "password": "hello123"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "hello@hello.com",
  "password": "hello123"
}
